baseURL = "http://localhost:1313/gdr_nbody_2021/"
#baseURL = "https://lcpq.github.io/gdr_nbody_2021/"
canonifyurls  = true
languageCode = "en-us"
DefaultContentLanguage = "en"
theme = "beautifulhugo"
title = "GDR NBODY MEETING (Toulouse, 10-13 Jan 2022)"
[Params]
  hometitle = "GDR NBODY GENERAL MEETING 2022"
  logo="img/CNRS.png"
#  subtitle = ""
[[Params.bigimg]]
  src = "img/500px-Maths1.jpg"
  desc = "GDR NBODY"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
 [Author]
#  name = "GDR NBODY"
   email = "gdrnbody@lct.jussieu.fr"
#  github = "LCPQ"
   twitter = "GDR_NBODY"
#   youtube = "channel/UCPUtUMqEM3K5sYcMJGTd_Bg"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[[menu.main]]
    name = "Registration"
    url = "registration"
    weight = 2

[[menu.main]]
    name = "Planning"
    url = "planning"
    weight = 3

 [[menu.main]]
     name="Presentations"
     url = "presentations"
     weight = 4

 [[menu.main]]
     name="Posters"
     url = "posters"
     weight = 5

[[menu.main]]
    name = "Location"
    url = "map"
    weight = 6

[[menu.main]]
    name = "Participants"
    url = "participants"
    weight = 7

[[menu.main]]
    name = "Sponsors"
    url = "sponsors"
    weight = 8

#[[menu.main]]
#    parent="external"
#    name = "CNRS"
#    url = "http://www.cnrs.fr"
#    weight = 2

