baseURL = "http://localhost:1313/yrm2024/"
#baseURL = "https://lcpq.github.io/yrm2024/"
canonifyurls  = true
languageCode = "en-us"
DefaultContentLanguage = "en"
theme = "beautifulhugo"
title = "20th ETSF Young Researchers' Meeting 2024 (Toulouse, 27-31 May 2024)"
#title = "YRM 2024, 27-31 May, Toulouse"
[Params]
  hometitle = "YRM 2024"
#  hometitle = "27-31 May Toulouse"
#  hometitle = " "
#  logo="img/yrm-2024-logo.png"
#  subtitle = "ETSF"
  subtitle = "27-31 May, Toulouse"
 # since = "2024"
[[Params.bigimg]]
  src = "img/Toulouse_12.png"
  desc = "YRM 2024"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
 [Author]
#   name = "YRM 2024"
   email = "yrm2024organizers@gmail.com"
#  github = "LCPQ"
#   twitter = "GDR_NBODY"
#   youtube = "channel/UCPUtUMqEM3K5sYcMJGTd_Bg"


[[menu.main]]
    name = "Overview"
    url = "event"
    weight = 1

[[menu.main]]
    name = "Registration"
    url = "registration"
    weight = 2

[[menu.main]]
    name = "Program"
    url = "program"
    weight = 3

 [[menu.main]]
     name="Speakers"
     url = "speakers"
     weight = 4

# [[menu.main]]
#     name="Posters"
#     url = "posters"
#     weight = 5

[[menu.main]]
    name = "Location"
    url = "map"
    weight = 5

[[menu.main]]
    name = "Participants"
    url = "participants"
    weight = 6

[[menu.main]]
    name = "Organizers"
    url = "organizers"
    weight = 7

[[menu.main]]
    name = "Sponsors"
    url = "sponsors"
    weight = 8

#[[menu.main]]
#    parent="external"
#    name = "CNRS"
#    url = "http://www.cnrs.fr"
#    weight = 2

